### ISSUE TITLE
Speed and Efficiency Comparisons

### ISSUE THREAD

**Issue by TysonStanley** [markfairbanks/tidydt#1]
@markfairbanks it may be beneficial to show how these functions compare with the Tidyverse functions in terms of speed and efficiency (can use the updated `bench` package to do so). This is probably the main draw to this package--the idea that someone has a more efficient and a quicker experience than if they were using the Tidyverse.

**Comment by markfairbanks** [comment]
Sounds like a good idea - I'll start working on this

**Comment by markfairbanks** [comment]
@TysonStanley Is there a way to put together the results without it being on the README? That way I can avoid rerunning everything from scratch for every small edit made

**Comment by TysonStanley** [comment]
I think what you did on the README looks great but yes, I like using a vignette in the package or a Wiki page on GitHub.

**Comment by TysonStanley** [comment]
Also, do you have a Twitter account? It is a very active place for the R community (often it is where I share updates to packages and such).

**Comment by markfairbanks** [comment]
Haha actually I made my first comment yesterday on Twitter because someone sent me an email on my GitHub listed email to let me know people were talking about `tidydt`. My handle is @GoodAboutHood_. I'll look into being more active on there.

Also I'm going to close this issue since I'm in the process of adding speed comps. Thanks again for the suggestion!
